/* Interfaces with the Macro Facility */

/* - The DATA step, the SAS Component Language, and the SQL procedure provide interfaces with the macro facility. 
The following tables list the elements that interact with the SAS macro facility. */

/* ~ An interface with the macro facility is not part of the macro processor but rather a SAS 
software feature that enables another portion of the SAS language to interact with the 
macro facility during execution. For example, a DATA step interface enables you to 
access macro variables from the DATA step. Macro facility interfaces are useful because, 
in general, macro processing happens before DATA step, SQL, SCL, or SAS/CONNECT 
execution. The connection between the macro facility and the rest of SAS is not usually 
dynamic. But by using an interface to the macro facility, you can dynamically connect 
the macro facility to the rest of SAS */






/* Interacting with the Macro Facility during DATA Step Execution */




/* CALL EXECUTE */

/* ~ Call Execute is a facility of the DATA step which allows executing SAS code generated by the DATA step. Also, the
data from the DATA step can be used as part of the executable code in the Call Execute.*/

/* syntax:

call execute('argument');

 */

/* 01 */
data _null_;
    call execute('%put Hello world;');
run;

/*02*/
data _null_;
    set sashelp.class;
   call execute('%put Students name is '||strip(name)||'; ');
run;

/*03*/
data _null_;
     set sashelp.class;
     call execute('data work.'||strip(name)||';
                     set sashelp.class;
                     where name="'||strip(name)||'";
                   run;');
run;


/* 04 */
%macro datasets(name= );
     data work.&name;
          set sashelp.class;
          where name="&name";
     run;
%mend datasets;
data _null_;
     set sashelp.class;
     call execute('%datasets(name='||strip(name)||');');
run;

%datasets(name=Alfred); 
%datasets(name=Alice); 
%datasets(name=Barbara);



/* 05 */

proc sql;
   create table work.Vars as
         select name,type
         from dictionary.columns
         where memname="CLASS" and libname="SASHELP";
quit;
%macro report(var= , type= );
       %if &type=char %then %do;
          proc freq data=sashelp.class;
               table &var;
          run;
       %end;
       %else %do;
       proc means data=sashelp.class;
            var &var;
       run;
       %end;
%mend report;
data _null_;
     set work.Vars;
     call execute('%report(var='||strip(name)||' , type='||strip(type)||');');
run;


       /* Cue: Code generated and executed by Call Execute:
       
                %report(var=Age , type=num);
                %report(var=Sex , type=char);
                %report(var=Age , type=num);
                %report(var=Height , type=num);
                %report(var=Weight , type=num); */
               
               
               
               



/* Using SAS Language Functions in the DATA Step and Macro Facility */

/* %SYSFUNC function*/

/* syntax:

%SYSFUNC(function(arguments)<, format>)

 */

%let x=%sysfunc(trim(%sysfunc(left(&num))));

%put Result: %sysfunc(mean(83, 6 * 2, %sysfunc(divide(50,2))));

%put title "%sysfunc(date(),worddate.) Absence Report";




%let string1 = V01N01-V01N10;
%let string1 = %sysfunc(translate(&string1,P, N));
%put With N translated to P, V01N01-V01N10 is &string1;

         /* Note: TRANSLATE function replaces specific characters in a character expression. 
                 syntax: 
                     TRANSLATE(expression, to-characters, from-characters)
                                                                             */
                                                                            


/* Because %SYSFUNC is a macro function, you do not need to enclose character values 
in quotation marks as you do in SAS language functions. For example, the arguments to 
the OPEN function are enclosed in quotation marks when the function is used alone but 
do not require quotation marks when used within %SYSFUNC. */


*using alone;
dsid = open("sashelp.Houses","i");
dsid = open("&mydata","&mode");

*with %SYSFUNC;
%let dsid = %sysfunc(open(sashelp.Houses,i));
%let dsid = %sysfunc(open(&mydata,&mode));










/* Interfaces with the SAS Component Language */

/* 
# SYMGET - Returns the value of a global macro variable during SCL execution. 

# SYMGETN - Returns the value of a global macro variable as a numeric value.

# CALL SYMPUT - Assigns a value produced in SCL to a global macro variable.

# CALL SYMPUTN - Assigns a numeric value to a global macro variable.
*/




/* SYMGET */

data _null_;
     set sashelp.class;
     if _N_ = 1 then do;
         call symput('nvar', name);
     end;
run;
%put &nvar;
*Get macro variable value in a dataset;
data want;
     var1=symget('nvar');
run;



/* This example assigns the value of macro variable G to the DATA step variable X. */
x=symget('g');
















